/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adept_arandroid_ArjRobot */

#ifndef _Included_com_adept_arandroid_ArjRobot
#define _Included_com_adept_arandroid_ArjRobot
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    initialize
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_adept_arandroid_ArjRobot_initialize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_adept_arandroid_ArjRobot_shutdown
  (JNIEnv *, jobject);
  
/*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    gotoGoal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_adept_arandroid_ArjRobot_gotoGoal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_adept_arandroid_ArjRobot_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    waitGoalDone
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_adept_arandroid_ArjRobot_waitGoalDone
  (JNIEnv *, jobject, jint);
  
/*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    getRobotStatus
 * Signature: ()jdoubleArray
 */
JNIEXPORT jdoubleArray JNICALL Java_com_adept_arandroid_ArjRobot_getRobotStatus
  (JNIEnv *, jobject);
  
/*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    getGoals
 * Signature: ()jobjectArray
 */
JNIEXPORT jobjectArray JNICALL Java_com_adept_arandroid_ArjRobot_getGoals
  (JNIEnv *, jobject);
  
  /*
 * Class:     com_adept_arandroid_ArjRobot
 * Method:    getMap
 * Signature: ()jdoubleArray
 */
JNIEXPORT jdoubleArray JNICALL Java_com_adept_arandroid_ArjRobot_getMap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
